// src/components/Navigation/index.tsx
import { Link } from 'preact-router';
import {
  mdiAccountMusic,
  mdiAlbum,
  mdiCog,
  mdiFolderMusic,
  mdiMusicNote,
  mdiPlaylistMusic,
} from '@mdi/js';
import { Icon } from '../icon';
import { nav, link } from './index.css';

const Entry = ({ href, path, text }: { href: string; path: string; text: string }) => (
  <Link href={href} class={link}>
    <Icon path={path} />
    {text}
  </Link>
);

export const Navigation = () => (
  <nav class={nav}>
    <Entry href='/artists' path={mdiAccountMusic} text='Artists' />
    <Entry href='/albums' path={mdiAlbum} text='Albums' />
    <Entry href='/tracks' path={mdiMusicNote} text='Tracks' />
    <Entry href='/playlists' path={mdiPlaylistMusic} text='Playlists' />
    <Entry href='/folders' path={mdiFolderMusic} text='Folders' />
    <Entry href='/settings' path={mdiCog} text='Settings' />
  </nav>
);

// src/frontend/components/Navigation.vue
<script setup lang="ts">
  import { RouterLink } from 'vue-router';

  const mainLinks = [
    { href: '/search', icon: 'i-mdi-search', title: 'Search' },
    { href: '/tracks', icon: 'i-mdi-music-note', title: 'Tracks' },
    { href: '/albums', icon: 'i-mdi-disk', title: 'Albums' },
    { href: '/artists', icon: 'i-mdi-account-multiple-outline', title: 'Artists' },
    { href: '/album-artists', icon: 'i-mdi-account-music-outline', title: 'Album Artists' },
    { href: '/settings', icon: 'i-mdi-cog-outline', title: 'Settings' },
  ];
</script>

<template>
  <nav>
    <ul>
      <li v-for="link of mainLinks">
        <RouterLink :to="link.href">
          <div :class="link.icon" />
          {{ link.title }}
        </RouterLink>
      </li>
    </ul>

    <RouterLink to="/about">
      <div class="i-mdi-information-outline" />
      About
    </RouterLink>
  </nav>
</template>
